services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: dicom-backend
    environment:
      - DUCKDB_PATH=/data/app.duckdb
    volumes:
      - duckdb_data:/data
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=http://backend:8000
    container_name: dicom-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  duckdb_data:
